version: "3"
services: 
    homeassistant:
        container_name: homeassistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        volumes:
            - /PATH_TO_CONFIG:/config
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        privileged: true
        network_mode: host

    esphome:
        container_name: esphome
        image: "esphome/esphome:latest"
        restart: unless-stopped
        ports:
            - "8081:6052"
